Feature/tests
VeraLapidus/showroom pull request #5
Opened 2023-01-19 10:29 UTC by VeraLapidus

2023-01-19 11:16 UTC, shprexen requested changes
In general - you've done it pretty good
Add tests for celery tasks logic, as well for stats endpoints
I recommend you to use `coverage` tool, to see how many rows of code have been covered by tests. We should aim for 90 percent coverage

2023-01-19 11:16 UTC, shprexen commented on auto_show/tests.py
> +    assert User.objects.filter(username="Ford Minsk").exists()
We don't test Django functions
We should focus on implemented business logic

2023-01-25 11:35 UTC, shprexen requested changes

2023-01-25 11:35 UTC, shprexen commented on auto_show/tests.py
> +    response = api_client.get(url, pk=create_auto_show.id)
test, if response body is valid

2023-01-25 14:23 UTC, VeraLapidus commented on auto_show/tests.py
> +    response = api_client.get(url, pk=create_auto_show.id)
done

2023-01-27 11:41 UTC, shprexen requested changes
check authentication of endpoints, add requests for unauthorized actions to check 403 status code

2023-01-31 11:44 UTC, shprexen requested changes

2023-01-31 11:44 UTC, shprexen commented on deals/tests.py
> +    assert response.status_code == 403
use builtin status codes `from rest_framework import status`, for example: `status.HTTP_404_NOT_FOUND`
According to DRF docs:
"Using bare status codes in your responses isn't recommended. REST framework includes a set of named constants that you can use to make your code more obvious and readable."

2023-02-01 11:22 UTC, shprexen approved these changes

2023-02-02 07:32 UTC, merged